name: 小红书 Hop
icon: file:icon.png
identifier: com.ajanlab.popclip.xiaohongshu-hop
popclip version: 4631    # 4631 = PopClip 2023.11
version: 1.0.2
description: Select any text to search Xiaohongshu instantly, or open a shared note directly from its link.

actions:
  - title: 小红书
    icon: file:icon.png
    requirements: [text]
    shell script file: Source/xiaohongshu-hop.sh
